package dev.projects.backend.enums;

public enum BusinessCategory {
    PHOTOGRAPHER,
    VIDEOGRAPHER,
    BEAUTY_SALON,
    DRESSES,
    SUITS,
    HAIR_DRESSER,
    BRIDAL_SALON,
    DECOR_LIGHTNING,
    DJ,
    MUSICIAN,
    FLORIST,
    JEWELER,
    CEREMONY_VENUE,
    WEDDING_VENUE,
    CATERER,
    HOTEL_ROOMS,
    BAKERY,
    TRANSPORTATION,
    TRAVEL_AGENT,
    ACCESSOIRES_FAVORS,
    WEDDING_PLANNER,
    INVITATION_PAPER_GOODS,
    BAR_SERVICE,
    ENTERTAINMENT
}
